# Utilisation de l'image officielle Node.js
FROM node:latest

# Définition du répertoire de travail
WORKDIR /app

# Copie des fichiers package.json et package-lock.json
COPY package*.json ./

# Installation des dépendances
RUN npm install

# Copie du reste du code
COPY . .

# Exposition du port de Vite.js
EXPOSE 5173

# Commande pour démarrer Vite
CMD ["npm", "run", "dev", "--", "--host"]
