services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb://mongo:27017/  # URI MongoDB corrigée
      - JWT_SECRET=secret
      - SERVER_PORT=5000
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
